Web/Sa_finalproject/Controllers/CRUDProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sa_finalproject.Models;

namespace Sa_finalproject.Controllers
{
    public class CRUDProductsController : Controller
    {
        private Model1 db = new Model1();

        // GET: CRUDProducts
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: CRUDProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: CRUDProducts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CRUDProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,Price,Detail,Imange,CategoryByID,Quanlity,Sale")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: CRUDProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: CRUDProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,Price,Detail,Imange,CategoryByID,Quanlity,Sale")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: CRUDProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: CRUDProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Sa_finalproject/Controllers/ProductController.cs
using Sa_finalproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sa_finalproject.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ProductDetail(int proid)
        {
            Model1 db = new Model1();
            Product pro = db.Products.Where(p => p.ProductID == proid).SingleOrDefault();
            return View(pro);
        }
        [ChildActionOnly]
        public ActionResult Category()
        {
            Model1 db = new Model1();
            List<Category> catList = db.Categories.ToList();
            return PartialView(catList);
        }

        public ActionResult CatList(int danhMucID)
        {
            Model1 db = new Model1();
            List<Product> danhSachLoaiSanPham = (from p in db.Products where p.CategoryByID == danhMucID select p).ToList();
            return View(danhSachLoaiSanPham);
        }
        [ChildActionOnly]
        public ActionResult SaleProduct()
        {
            Model1 db = new Model1();
            List<Product> saleList = (from s in db.Products where s.Sale == 1 select s).ToList();
            return PartialView(saleList);

        }
    }
}

Web/Sa_finalproject/Controllers/UserController.cs
using Sa_finalproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Sa_finalproject.Controllers
{
    public class UserController : Controller
    {
        Model1 db = new Model1();

        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(UserModel user)
        {
            try
            {
                Model1 db = new Model1();
                if (ModelState.IsValid == true)
                {
                    UserManager usermanager = new UserManager();
                    if (usermanager.checkUserName(user.UserName) == true && usermanager.checkEmail(user.Email) == true)
                    {
                        Customer user2 = new Customer();
                        user2.UserName = user.UserName;
                        user2.TenKhachHang = user.TenKhachHang;
                        user2.Password = user.Password;
                        user2.Email = user.Email;
                        user2.SDT = user.SoDienThoai;
                        user2.DiaChi = user.DiaChi;
                        // ma hoa password
                        SHA256 sha256 = new SHA256CryptoServiceProvider();
                        Byte[] originalBytes = ASCIIEncoding.Default.GetBytes(user2.Password);
                        Byte[] encodedBytes = sha256.ComputeHash(originalBytes);
                        user2.Password = BitConverter.ToString(encodedBytes);
                        db.Customers.Add(user2);
                        db.SaveChanges();
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.error = "Tai khoan hoac email da ton tai";
                    }

                    ViewBag.dangkythanhcong = "đã đăng ký thành công";
                }
            }
            catch (Exception ex)
            {

            }

            return View();

        }
        public ActionResult FailRegister()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection f)
        {
            if (ModelState.IsValid)
            {
                string taikhoan = f["TxtTaikhoan"].ToString();
                string matkhau = f["TxtMatkhau"].ToString();
                Model1 db = new Model1();
                SHA256 sha = new SHA256CryptoServiceProvider();
                Byte[] originalBytes = ASCIIEncoding.Default.GetBytes(matkhau);
                Byte[] encodedBytes = sha.ComputeHash(originalBytes);
                matkhau = BitConverter.ToString(encodedBytes);
                var username = db.Customers.Where(u => u.UserName == taikhoan).Select(u => u.UserName).SingleOrDefault();
                //Customer c = db.Customers.SingleOrDefault(x => x.UserName == taikhoan && x.Password == matkhau);
                UserManager userManager = new UserManager();
                if (userManager.checkLogin(taikhoan, matkhau) == true)
                {

                    Session["Logged"] = username;
                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    ViewBag.thongbao = "Tên tài khoản hoặc mật khẩu sai";
                    return View();
                }
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session["Logged"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

Web/Sa_finalproject/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "LayoutPage1";
}



<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Web Store Template</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <!-- templatemo 341 web store -->
    <!--
    Web Store Template
    http://www.templatemo.com/preview/templatemo_341_web_store
    -->
    <link href="~/css/templatemo_style.css" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" type="text/css" href="~/css/ddsmoothmenu.css" />

    <script type="text/javascript" src="~/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/ddsmoothmenu.js">
        @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@

/***********************************************
* Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

    </script>

    <script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "templatemo_menu", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

    </script>

    <link rel="stylesheet" type="text/css" href="~/css/styles.css" />
    <script language="javascript" type="text/javascript" src="~/scripts/mootools-1.2.1-core.js"></script>
    <script language="javascript" type="text/javascript" src="~/scripts/mootools-1.2-more.js"></script>
    <script language="javascript" type="text/javascript" src="~/scripts/slideitmoo-1.1.js"></script>
    <script language="javascript" type="text/javascript">
	window.addEvents({
		'domready': function(){
			/* thumbnails example , div containers */
			new SlideItMoo({
						overallContainer: 'SlideItMoo_outer',
						elementScrolled: 'SlideItMoo_inner',
						thumbsContainer: 'SlideItMoo_items',
						itemsVisible: 5,
						elemsSlide: 2,
						duration: 200,
						itemsSelector: '.SlideItMoo_element',
						itemWidth: 171,
						showControls:1});
		},

	});

	function clearText(field)
	{
		if (field.defaultValue == field.value) field.value = '';
		else if (field.value == '') field.value = field.defaultValue;
	}
    </script>

</head>

<body id="home">

    <div id="templatemo_wrapper">
        <div id="templatemo_header">
            <div id="site_title">
                <h1><a href="#">Free Website Template</a></h1>
            </div>

            <div id="header_right">
                <ul id="language">
                    <li><a><img src="~/images/usa.png" alt="English" /></a></li>
                    <li><a><img src="~/images/china.png" alt="Chinese" /></a></li>
                    <li><a><img src="~/images/germany.png" alt="Germany" /></a></li>
                    <li><a><img src="~/images/india.png" alt="Indian" /></a></li>
                </ul>
                <div class="cleaner"></div>
                <div id="templatemo_search">
                    <form action="#" method="get">
                        <input type="text" value="Search" name="keyword" id="keyword" title="keyword" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field" />
                        <input type="submit" name="Search" value="" alt="Search" id="searchbutton" title="Search" class="sub_btn" />
                    </form>
                </div>
            </div> <!-- END -->
        </div> <!-- END of header -->

        <div id="templatemo_menu" class="ddsmoothmenu">
            <ul>
                <li><a href="index.html" class="selected">Home</a></li>
                <li>
                    <a href="@Url.Action("Index","CRUDProducts")">Products</a>    
                </li>
                <li>
                    <a href="about.html">About</a>
                    <ul>
                        <li><a href="#">Sub menu 1</a></li>
                        <li><a href="#">Sub menu 2</a></li>
                        <li><a href="#">Sub menu 3</a></li>
                        <li><a href="#">Sub menu 4</a></li>
                        <li><a href="#">Sub menu 5</a></li>
                    </ul>
                </li>
                <li><a href="@Url.Action("Register","User")">Register</a></li>
                @if (Session["Logged"] != null)
                {
                    <li><a href="@Url.Action("Logout","User")">Log out</a></li>
                    <li style="margin-top: 13px">Hi! @Session["Logged"]</li>
                }
                else
                {
                    <li><a href="@Url.Action("Login","User")">Login</a></li>
                }
                <li>
                    @Html.Action("HeaderCard", "Cart")

                </li>

            </ul>
            <br style="clear: left" />
        </div> <!-- end of templatemo_menu -->

        <div id="templatemo_middle">
            <img src="~/images/templatemo_image_01.png" alt="Image 01" />
            <h1>Introducing Web Store</h1>
            <p>Web Store is a free css template for your personal or commercial websites. Feel free to download, edit and use this template for any purpose.</p>
            <a href="#" class="buy_now">Browse All Products</a>
        </div> <!-- END of middle -->

        <div id="templatemo_main_top"></div>
        <div id="templatemo_main">
            <div id="product_slider">
                <div id="SlideItMoo_outer">
                    <div id="SlideItMoo_inner">
                        <div id="SlideItMoo_items">
                            <div class="SlideItMoo_element">
                                <a href="#slide1" target="_parent">
                                    <img src="~/images/gallery/01.jpg" alt="product 1" />
                                </a>
                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#slide2" target="_parent">
                                    <img src="~/images/gallery/02.jpg" alt="product 2" />
                                </a>
                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#slide3" target="_parent">
                                    <img src="~/images/gallery/03.jpg" alt="product 3" />
                                </a>
                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#slide4" target="_parent">
                                    <img src="~/images/gallery/04.jpg" alt="product 4" />
                                </a>
                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#slide5" target="_parent">
                                    <img src="~/images/gallery/05.jpg" alt="product 5" />
                                </a>
                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#slide6" target="_parent">
                                    <img src="~/images/gallery/06.jpg" alt="product 6" />
                                </a>
                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#slide6" target="_parent">
                                    <img src="~/images/gallery/07.jpg" alt="product 7" />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cleaner"></div>
            </div>

            @*<div id="sidebar">
                    <h3>Categories</h3>
                    <ul class="sidebar_menu">
                        <li><a href="#">Aenean et dolor diam</a></li>
                        <li><a href="#">Aenean pulvinar</a></li>
                        <li><a href="#">Cras bibendum auctor</a></li>
                        <li><a href="#">Donec sodales bibendum</a></li>
                        <li><a href="#">Etiam in tellus</a></li>
                        <li><a href="#">Hendrerit justo</a></li>
                        <li><a href="#">Integer interdum</a></li>
                        <li><a href="#">Maecenas a diam</a></li>
                        <li><a href="#">Nullam in semper</a></li>
                        <li><a href="#">Posuere in commodo</a></li>
                        <li><a href="#">Tincidunt leo</a></li>
                        <li><a href="#">Vestibulum blandit</a></li>
                    </ul>
                    <h3>Newsletter</h3>
                    <p>Praesent aliquam mi id tellus pretium pulvinar in vel ligula.</p>
                    <div id="newsletter">
                        <form action="#" method="get">
                            <input type="text" value="Subscribe" name="email_newsletter" id="email_newsletter" title="email_newsletter" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field" />
                            <input type="submit" name="subscribe" value="Subscribe" alt="Subscribe" id="subscribebtn" title="Subscribe" class="subscribebtn" />
                        </form>
                        <div class="cleaner"></div>
                    </div>
                </div>  END of sidebar*@
            @*lien ket toi partialView*@
            @Html.Action("Category", "Product")


            <div id="content">




                @RenderBody()






            </div> <!-- END of content -->
            <div class="cleaner"></div>
        </div> <!-- END of main -->

        <div id="templatemo_footer">
            <div class="col col_16">
                <h4>Categories</h4>
                <ul class="footer_menu">
                    <li><a href="#">Aenean et dolor diam</a></li>
                    <li><a href="#">Aenean pulvinar</a></li>
                    <li><a href="#">Cras bibendum auctor</a></li>
                    <li><a href="#">Donec sodales bibendum</a></li>
                </ul>
            </div>
            <div class="col col_16">
                <h4>Pages</h4>
                <ul class="footer_menu">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Shipping</a></li>
                    <li><a href="#">Privacy</a></li>
                </ul>
            </div>
            <div class="col col_16">
                <h4>Partners</h4>
                <ul class="footer_menu">
                    <li><a href="#">Website Templates</a></li>
                    <li><a href="#">HTML CSS Layouts</a></li>
                    <li><a href="#">Web Design</a></li>
                    <li><a href="#">Free Graphics</a></li>
                </ul>
            </div>
            <div class="col col_16">
                <h4>Social</h4>
                <ul class="footer_menu">
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Youtube</a></li>
                    <li><a href="#">LinkedIn</a></li>
                </ul>
            </div>
            <div class="col col_13 no_margin_right">
                <h4>About Us</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper quam sit amet turpis rhoncus id venenatis tellus sollicitudin. Fusce ullamcorper, dolor non mollis pulvinar, turpis tortor commodo nisl. Validate <a href="http://validator.w3.org/check?uri=referer" rel="nofollow"><strong>XHTML</strong></a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow"><strong>CSS</strong></a>.</p>
            </div>

            <div class="cleaner h40"></div>
            <center>
                Copyright © 2048 Your Company Name
            </center>
        </div> <!-- END of footer -->

    </div>

</body>
</html>